### ISSUE TITLE
Duplicating of ds-params (still)

### ISSUE THREAD

**Issue by moretaste** [brendo/uniondatasource#42] opened 2014-09-18 07:34 UTC
I'm still not convinced that https://github.com/brendo/uniondatasource/issues/40 is solved.

I understand that parameters doesn't have to be unique. But that isn't the problem.

The problem is that the parameters are duplicates (maybe the word repeat wasn't the right one). The more entries I make the more duplicates I got.

**Comment by nilshoerrmann** [comment] 2015-06-04 18:45
I just encountered this bug as well and it's caused by this line:
https://github.com/brendo/uniondatasource/commit/f5c226d08762608959815b9d75487262e4561fd3#diff-1ba9d55430a6916bdaf92be9ae651b2bR1068

The extension duplicates all output parameters that have not been an array before. The bug is breaking is breaking sites that rely on comparing parameter values because strings become arrays and thus the XML structure changes.

What's that line doing?

**Comment by nilshoerrmann** [comment] 2015-06-04 18:50
Uncommenting that line fixes the issue for me.

**Comment by moretaste** [comment] 2017-02-10 06:27
Changing line https://github.com/brendo/uniondatasource/commit/f5c226d08762608959815b9d75487262e4561fd3#diff-1ba9d55430a6916bdaf92be9ae651b2bR1068

`array_merge_recursive` to `array_replace_recursive` seems to solve it. (Not yet fully tested)

**Comment by nitriques** [comment] 2017-03-22 21:26
@moretaste wanna send a PR ?

**Comment by brendo** [comment] 2017-03-24 00:28
Closed by #47

**Closed** 2017-03-24 00:33 UTC
